### ISSUE TITLE
Avoid using hard-coded raw tx

### ISSUE THREAD

**Issue by 2dvorak** [klaytn/klaytn-rpc-tester#19]
Could this [raw tx](https://github.com/klaytn/klaytn-rpc-tester/blob/6883c4d342dfe2f66cfc366dde8405e6a4421d93/main.py#L672) be assembled on-the-fly using config? I was testing with local network and got error because of mismatched chain ID.

cc. @JayChoi1736

**Comment by JayChoi1736** [comment]
i had no way to make raw transaction in python at that time.

now we can generate account update raw tx by web3py.

i will fix related parts

**Comment by yoomee1313** [comment]
I'll close this PR.
