### ISSUE TITLE
[API] A new candidate API

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn-rpc-tester#20]
@JayChoi1736, A [new API](https://github.com/klaytn/klaytn/pull/1996) is now on review. Once it is merged, could you consider updating this API to here, web3-klaytn, caver, and other dependencies?

Thank you.

**Comment by JayChoi1736** [comment]
okay. i will check.

**Comment by yoomee1313** [comment]
I'll close this PR.
